# UV Package Manager Configuration
# Reference: https://github.com/astral-sh/uv

[install]
# Don't compile bytecode during installation for faster installs
compile-bytecode = false

[pip]
# Use the default index
index-url = "https://pypi.org/simple"

# Cache configuration
[cache]
# Cache directory will use UV_CACHE_DIR env var or default to ~/.cache/uv

[tool]
# Enable dependency locking
enable-lock = true
